import { test } from "bun:test";
import assert from "node:assert/strict";
import { createInitialState, resolveFn } from "../dist/index.js";

// genesis — structure-producing formulas (genesis-segment.md, accepted).
// A generator formula's value {genesis:true, cels:{…}} commits a batch
// stamped generatedBy; generators are authoritative: regeneration
// diffs, user data plane survives, deletion sweeps the bloom.

const v = (state, key) => state.cels.get(key)?.v;
// flush pending requests, then run the drain once with an empty batch:
// the targeted flush skips empty queues, but an edit that REMOVED a
// generator enqueues nothing and must still sweep (the defn lesson).
const flush = async (state) => {
  await resolveFn(state, "drain")(state, "genesis.commit");
  await resolveFn(state, "genesis.drain")([], state);
};
const cycleAndFlush = async (state) => {
  await resolveFn(state, "runCycle")(state);
  return flush(state);
};
const seedUser = (state, key, spec) =>
  resolveFn(state, "setCel")(state, key, { ...spec, metadata: { segment: "user", ...spec.metadata } });
const isErr = (x) => !!x && typeof x === "object" && x.kind === "error";

test("a grid generator blooms cells; deleting the formula sweeps them (THE north-star invariant)", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 2 2 "gng")' });
  await cycleAndFlush(state);

  for (const k of ["gng.A1", "gng.A2", "gng.B1", "gng.B2", "gng.dims"]) {
    const cel = state.cels.get(k);
    assert.ok(cel, `${k} bloomed`);
    assert.equal(cel.metadata.generatedBy, "maker", "ownership stamped");
    assert.equal(cel.metadata.segment, "gng", "layer segment stamped");
  }
  assert.deepEqual(v(state, "gng.dims"), { rows: 2, cols: 2 });

  // replace the generator with a plain formula → bloom unmade
  await seedUser(state, "maker", { celType: "FormulaCel", f: "(+ 1 1)" });
  await cycleAndFlush(state);
  assert.equal(v(state, "maker"), 2, "ex-generator is an ordinary formula");
  for (const k of ["gng.A1", "gng.A2", "gng.B1", "gng.B2", "gng.dims"]) {
    assert.equal(state.cels.get(k), undefined, `${k} swept`);
  }
});

test("infix generators work: =grid(2, 2, \"h\")", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", {
    celType: "FormulaCel", f: '=grid(2, 2, "gnh")', metadata: { parser: "infix" },
  });
  await cycleAndFlush(state);
  assert.ok(state.cels.get("gnh.A1"), "infix-parsed generator bloomed");
  assert.equal(state.cels.get("gnh.A1").metadata.generatedBy, "maker");
});

test("regeneration: user content survives a grow; shrink retires the removed cells", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 2 2 "gng")' });
  await cycleAndFlush(state);

  // the user types into a generated cell — data plane
  await resolveFn(state, "setValue")(state, "gng.A1", 42);
  assert.equal(v(state, "gng.A1"), 42);

  // grow 2×2 → 3×2: A1 untouched (unchanged spec), A3 appears
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 3 2 "gng")' });
  await cycleAndFlush(state);
  assert.equal(v(state, "gng.A1"), 42, "user's value survived regeneration");
  assert.ok(state.cels.get("gng.A3"), "new row bloomed");

  // shrink to 1×1: only A1 (+dims) remain
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 1 1 "gng")' });
  await cycleAndFlush(state);
  assert.equal(v(state, "gng.A1"), 42, "survivor keeps user content");
  assert.equal(state.cels.get("gng.A3"), undefined, "removed spec retired");
  assert.equal(state.cels.get("gng.B1"), undefined, "removed spec retired");
});

test("idempotent re-fire: same request leaves everything untouched", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 2 1 "gng")' });
  await cycleAndFlush(state);
  await resolveFn(state, "setValue")(state, "gng.A2", "kept");
  const a2 = state.cels.get("gng.A2");
  // touch the generator's world without changing its output
  await resolveFn(state, "runCycle")(state);
  await flush(state);
  assert.equal(state.cels.get("gng.A2"), a2, "cel object identity preserved on idempotent drain");
  assert.equal(v(state, "gng.A2"), "kept");
});

test("foreign keys are refused with ONE aggregated error; locked keys always refused", async () => {
  const state = createInitialState();
  await seedUser(state, "makerA", { celType: "FormulaCel", f: '(grid 1 1 "gnshared")' });
  await cycleAndFlush(state);
  await seedUser(state, "makerB", { celType: "FormulaCel", f: '(grid 1 2 "gnshared")' });
  await cycleAndFlush(state);
  const b = v(state, "makerB");
  assert.ok(isErr(b), "intruding generator traps");
  assert.match(b.message, /generated by makerA/);
  assert.ok(state.cels.get("gnshared.A1"), "original bloom intact");
  assert.equal(state.cels.get("gnshared.A1").metadata.generatedBy, "makerA");
});

test("stale consumers of a swept bloom trap with undefined-symbol", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 1 1 "gng")' });
  await cycleAndFlush(state);
  await resolveFn(state, "setValue")(state, "gng.A1", 5);
  await seedUser(state, "reader", { celType: "FormulaCel", f: "(* gng.A1 2)" });
  await resolveFn(state, "runCycle")(state);
  assert.equal(v(state, "reader"), 10);

  await seedUser(state, "maker", { celType: "FormulaCel", f: "(+ 0 0)" });
  await cycleAndFlush(state);
  const r = v(state, "reader");
  assert.ok(isErr(r) || r === undefined || Number.isNaN(r), "reader no longer computes against the swept cell");
});

test("ownership joins segment ADJACENCY (dormancy visibility), never the cascade", async () => {
  const state = createInitialState();
  await seedUser(state, "maker", { celType: "FormulaCel", f: '(grid 1 1 "gng")' });
  await cycleAndFlush(state);
  const indexes = state.cels.get("precomputedStates")?.v;
  const adj = indexes?.segmentAdjacency;
  assert.ok(adj?.get("gng")?.has("user"), "layer segment depends on its generator's segment");
  // and the children index must NOT contain an ownership edge
  const children = indexes?.children;
  assert.ok(!(children?.get("maker")?.has("gng.A1")), "ownership is not a cascade edge");
});
