=cels("readme", 18, 1,
	geom(0, 0, 1, 1),
	at("a1", "plastron 🐢"),
	at("a2", "a spreadsheet that lives in ONE index.html — open it in any browser, no install, no server."),
	at("a3", "type a formula into a cell and press ⚡ (the fire button on the formula bar) to run it."),
	at("a4", ""),
	at("a5", "— try these: type one into a cell, then press ⚡ —"),
	at("a6", "•  =1+1          → 2"),
	at("a7", "•  =cels(8, 5)   → a worksheet of editable cels, each like this one"),
	at("a8", '•  =def("double", "js", "x => x * 2")   then   =double(21)   → 42'),
	at("a9", '•  =dom("h2", style("color", "tomato"), "hi")   → a styled element'),
	at("a10", '•  =canvas(300, 170, circle(150, 85, 12, "#ffd34e"))   → draw on a canvas'),
	at("a11", '•  =grok("say hi in 5 words", key)   → chat with an LLM (key = a cel holding your api key)'),
	at("a12", '•  =save("mywork")   → save this sheet to a file in 📁 Files; reopen with =open("mywork")'),
	at("a13", "•  =link()   → a shareable URL that rebuilds this whole sheet anywhere"),
	at("a14", "•  =doom()   → yes, DOOM"),
	at("a15", ""),
	at("a16", "the navpanel (top-left icons) opens the readme, keyboard, consent, files, vault and DOOM."),
	at("a17", "edit this readme: it's a real file — /readme.f in 📁 Files."),
	at("a18", "github.com/rheophile10/plastron"))
