import { chromium } from "playwright";
import { join, dirname } from "path"; import { fileURLToPath } from "url";
const bundle = join(dirname(fileURLToPath(import.meta.url)), "..", "dist/index.html");
const b = await chromium.launch({ executablePath:"/usr/bin/google-chrome", headless:true, args:["--no-sandbox","--disable-dev-shm-usage"] });
const page = await b.newPage();
const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
await page.goto("file://"+bundle); await page.waitForFunction(()=>!!globalThis.plastron,{timeout:8000}); await page.waitForTimeout(250);
const put=(src,key)=>page.evaluate(async([s,k])=>{const{state,resolveFn}=globalThis.plastron;await resolveFn(state,"origin.edit")(state,k);await resolveFn(state,"setValue")(state,"元.draft",s);await resolveFn(state,"origin.commit")(state,k);await new Promise(r=>setTimeout(r,140));return state.cels.get(k)?.v??null;},[src,key]);
let pass=0,fail=0; const ok=(c,w)=>{if(c){pass++;console.log("  ✔",w);}else{fail++;console.log("  ✘",w);}};
await put(`=grid(3, 1)`, "元");
await put(`1`, "g3x1.A1");
await put(`=g3x1!A1 + 1`, "g3x1.A2");
await put(`=g3x1!A2 + 1`, "g3x1.A3");
const g = await put(`=interlinked("g3x1")`, "元");
ok(g && g.tag === "canvas", "interlinked returns a canvas vnode");
const ops = (g && g.attrs && JSON.parse(g.attrs["data-ops"])) || [];
ok(ops.filter(o=>o.op==="circle").length === 3, "3 nodes (circles)");
ok(ops.filter(o=>o.op==="line").length === 2, "2 edges (lines)");
ok(ops.filter(o=>o.op==="text").length === 3, "3 node labels");
await page.waitForTimeout(200);
const drawn = await page.evaluate(()=>{ const cs=[...document.querySelectorAll("canvas[width='440']")]; if(!cs.length) return -1; const c=cs[cs.length-1]; const d=c.getContext("2d").getImageData(0,0,c.width,c.height).data; let nz=0; for(let i=3;i<d.length;i+=4) if(d[i]!==0)nz++; return nz; });
ok(drawn > 500, `force graph painted (${drawn} opaque px)`);
// --- def-driven bouncing ball ---
await put(`=def("ball", "js", "i => [30 + 280*Math.abs((i/20)%2-1), 30 + 200*Math.abs((i/14)%2-1)]")`, "元");
const sim = await put(`=simulate("ball", 120)`, "元");
ok(sim && sim.tag === "canvas", "simulate returns a canvas");
const sops = (sim && sim.attrs && JSON.parse(sim.attrs["data-ops"])) || [];
ok(sops.length===1 && sops[0].op==="frames" && sops[0].frames.length===120, "frames op with 120 trajectory points (physics from the def fn)");
await page.waitForTimeout(150);
const fh = () => page.evaluate(()=>{ const cs=[...document.querySelectorAll("canvas[width='360']")]; if(!cs.length)return -1; const c=cs[cs.length-1]; const d=c.getContext("2d").getImageData(0,0,c.width,c.height).data; let h=0; for(let i=0;i<d.length;i+=16)h=(h*31+d[i])|0; return h; });
const fa = await fh(); await page.waitForTimeout(450); const fb = await fh();
ok(fa!==-1 && fa!==fb, `ball ANIMATES over time (${fa} → ${fb})`);
ok(errs.length===0, "no console/page errors"+(errs.length?": "+errs.slice(0,2).join(" | "):""));
console.log(`\n${pass} passed, ${fail} failed`);
await b.close(); process.exit(fail?1:0);
